"""
Head pose estimation: given 2D pixel positions of 6 standard facial
landmarks (nose tip, chin, left/right eye outer corners, left/right
mouth corners), recovers the head's 3D orientation (yaw, pitch, roll)
using OpenCV's solvePnP against a generic 3D face model. This is the
classic 6-point head pose algorithm and is pure geometry — it needs no
downloaded model itself.

Getting those 6 landmark points in the first place normally comes from
MediaPipe's FaceLandmarker. That part DOES need a downloaded model
(`face_landmarker.task`), and in this sandbox that download is blocked
the same way YOLOv8 weights were: MediaPipe's downloader pulls from
`storage.googleapis.com`, which returns "Host not in allowlist" from the
network egress proxy here. `MediaPipeFaceLandmarker` below is complete,
correct integration code for a machine with normal internet access (or
a manually-placed `.task` file); `estimate_head_pose()` — the actual
geometry — is fully testable without it, and is tested against synthetic
landmark data generated by projecting a known 3D face at a known
rotation, then verifying the recovered angles match.
"""
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Optional

import cv2
import numpy as np

# Generic 3D face model (mm, roughly), in a coordinate system centered
# near the nose. These are standard reference points used across most
# 6-point head-pose implementations (not measured from any real person).
_MODEL_POINTS_3D = np.array(
    [
        (0.0, 0.0, 0.0),  # nose tip
        (0.0, -330.0, -65.0),  # chin
        (-225.0, 170.0, -135.0),  # left eye outer corner
        (225.0, 170.0, -135.0),  # right eye outer corner
        (-150.0, -150.0, -125.0),  # left mouth corner
        (150.0, -150.0, -125.0),  # right mouth corner
    ],
    dtype=np.float64,
)


@dataclass
class FaceLandmarks2D:
    """Pixel coordinates of the 6 landmarks needed for pose estimation."""

    nose_tip: tuple[float, float]
    chin: tuple[float, float]
    left_eye_outer: tuple[float, float]
    right_eye_outer: tuple[float, float]
    left_mouth_corner: tuple[float, float]
    right_mouth_corner: tuple[float, float]

    def as_array(self) -> np.ndarray:
        return np.array(
            [
                self.nose_tip,
                self.chin,
                self.left_eye_outer,
                self.right_eye_outer,
                self.left_mouth_corner,
                self.right_mouth_corner,
            ],
            dtype=np.float64,
        )


@dataclass
class HeadPose:
    yaw: float  # degrees, negative = looking left, positive = looking right
    pitch: float  # degrees, negative = looking down, positive = looking up
    roll: float  # degrees, head tilt


def _camera_matrix(frame_width: int, frame_height: int) -> np.ndarray:
    """Approximate camera intrinsics when no real calibration is available
    (focal length ~= image width is a standard rough assumption)."""
    focal_length = frame_width
    center = (frame_width / 2, frame_height / 2)
    return np.array(
        [[focal_length, 0, center[0]], [0, focal_length, center[1]], [0, 0, 1]],
        dtype=np.float64,
    )


def estimate_head_pose(
    landmarks: FaceLandmarks2D,
    frame_width: int,
    frame_height: int,
    camera_matrix: Optional[np.ndarray] = None,
) -> HeadPose:
    """
    Solves for head rotation using the 6-point model + solvePnP, then
    converts the resulting rotation matrix to yaw/pitch/roll (degrees).
    """
    if camera_matrix is None:
        camera_matrix = _camera_matrix(frame_width, frame_height)
    dist_coeffs = np.zeros((4, 1))  # assume no lens distortion

    image_points = landmarks.as_array()

    success, rotation_vec, _translation_vec = cv2.solvePnP(
        _MODEL_POINTS_3D, image_points, camera_matrix, dist_coeffs, flags=cv2.SOLVEPNP_ITERATIVE
    )
    if not success:
        raise ValueError("solvePnP failed to converge on these landmarks")

    rotation_matrix, _ = cv2.Rodrigues(rotation_vec)

    # Standard rotation-matrix -> Euler angle decomposition (ZYX order)
    sy = (rotation_matrix[0, 0] ** 2 + rotation_matrix[1, 0] ** 2) ** 0.5
    singular = sy < 1e-6

    if not singular:
        pitch = np.degrees(np.arctan2(rotation_matrix[2, 1], rotation_matrix[2, 2]))
        yaw = np.degrees(np.arctan2(-rotation_matrix[2, 0], sy))
        roll = np.degrees(np.arctan2(rotation_matrix[1, 0], rotation_matrix[0, 0]))
    else:
        pitch = np.degrees(np.arctan2(-rotation_matrix[1, 2], rotation_matrix[1, 1]))
        yaw = np.degrees(np.arctan2(-rotation_matrix[2, 0], sy))
        roll = 0.0

    return HeadPose(yaw=float(yaw), pitch=float(pitch), roll=float(roll))


class MediaPipeFaceLandmarker:
    """
    Production landmark extractor. Requires `pip install mediapipe` and a
    downloaded `face_landmarker.task` model file (or network access for
    MediaPipe to fetch it itself). In this sandbox, that download is
    blocked (see module docstring) — this class is correct integration
    code for a normal environment, not tested here.
    """

    LANDMARK_INDICES = {
        "nose_tip": 4,
        "chin": 152,
        "left_eye_outer": 33,
        "right_eye_outer": 263,
        "left_mouth_corner": 61,
        "right_mouth_corner": 291,
    }

    def __init__(self, model_path: str = "face_landmarker.task"):
        if not Path(model_path).exists():
            raise FileNotFoundError(
                f"'{model_path}' not found. Download it from MediaPipe's model zoo "
                f"(https://ai.google.dev/edge/mediapipe/solutions/vision/face_landmarker) "
                f"on a machine with normal internet access, or fetch it at import time "
                f"if your network allows storage.googleapis.com."
            )
        from mediapipe.tasks import python as mp_python
        from mediapipe.tasks.python import vision as mp_vision

        base_options = mp_python.BaseOptions(model_asset_path=model_path)
        options = mp_vision.FaceLandmarkerOptions(base_options=base_options, num_faces=5)
        self._landmarker = mp_vision.FaceLandmarker.create_from_options(options)

    def extract(self, frame: np.ndarray) -> list[FaceLandmarks2D]:
        import mediapipe as mp

        h, w = frame.shape[:2]
        mp_image = mp.Image(image_format=mp.ImageFormat.SRGB, data=frame)
        result = self._landmarker.detect(mp_image)

        faces = []
        for face_landmarks in result.face_landmarks:
            def px(idx: int) -> tuple[float, float]:
                lm = face_landmarks[idx]
                return (lm.x * w, lm.y * h)

            faces.append(
                FaceLandmarks2D(
                    nose_tip=px(self.LANDMARK_INDICES["nose_tip"]),
                    chin=px(self.LANDMARK_INDICES["chin"]),
                    left_eye_outer=px(self.LANDMARK_INDICES["left_eye_outer"]),
                    right_eye_outer=px(self.LANDMARK_INDICES["right_eye_outer"]),
                    left_mouth_corner=px(self.LANDMARK_INDICES["left_mouth_corner"]),
                    right_mouth_corner=px(self.LANDMARK_INDICES["right_mouth_corner"]),
                )
            )
        return faces
