"""
Recommendation & Optimization Engine
=====================================

Generates actionable retail recommendations from
consumer attention and store analytics.

This module is intentionally independent from the existing
AI detector and live_stats modules.

It can later be connected to FastAPI and the dashboards.
"""


# ==========================================================
# CONFIGURATION
# ==========================================================

DEFAULT_THRESHOLDS = {
    # Attention thresholds
    "high_attention": 70,
    "low_attention": 30,

    # Dwell time
    "high_dwell": 40,

    # Interaction
    "high_interaction": 10,
    "low_interaction": 2,

    # Traffic
    "high_traffic": 8,
    "low_traffic": 1,
}


# ==========================================================
# HELPER FUNCTIONS
# ==========================================================

def safe_number(value, default=0):
    """
    Safely convert a value into a number.
    """

    try:
        if value is None:
            return default

        return float(value)

    except (TypeError, ValueError):
        return default


def normalize_congestion(value):
    """
    Normalize congestion values.
    """

    if value is None:
        return "Unknown"

    return str(value).strip().lower()


def create_recommendation(
    priority,
    recommendation_type,
    target,
    action,
    reason,
    expected_impact,
    source="Recommendation Engine",
):
    """
    Create a standardized recommendation object.
    """

    return {
        "priority": priority,
        "type": recommendation_type,
        "target": target,
        "action": action,
        "reason": reason,
        "expected_impact": expected_impact,
        "source": source,
    }


# ==========================================================
# MAIN RECOMMENDATION FUNCTION
# ==========================================================

def generate_recommendations(
    analytics,
    camera_id=None,
    thresholds=None,
):
    """
    Generate optimization recommendations from
    existing store analytics.

    Parameters
    ----------
    analytics : dict
        Analytics generated by the existing system.

    camera_id : int | str | None
        Optional camera identifier.

    thresholds : dict | None
        Optional custom thresholds.

    Returns
    -------
    list
        List of recommendation dictionaries.
    """

    if not isinstance(analytics, dict):
        return [
            create_recommendation(
                priority="LOW",
                recommendation_type="System",
                target="Analytics",
                action="Wait for valid analytics data.",
                reason="Recommendation engine did not receive a valid analytics object.",
                expected_impact="Prevent invalid recommendations.",
            )
        ]

    # ------------------------------------------------------
    # Merge default and custom thresholds
    # ------------------------------------------------------

    config = DEFAULT_THRESHOLDS.copy()

    if isinstance(thresholds, dict):
        config.update(thresholds)

    # ------------------------------------------------------
    # Read existing analytics
    # ------------------------------------------------------

    current_persons = safe_number(
        analytics.get("current_persons")
    )

    total_customers = safe_number(
        analytics.get("total_customers")
    )

    average_dwell = safe_number(
        analytics.get("average_dwell")
    )

    attention_score = safe_number(
        analytics.get("attention_score")
    )

    product_interactions = safe_number(
        analytics.get("product_interactions")
    )

    tracked_paths = safe_number(
        analytics.get("tracked_paths")
    )

    store_congestion = normalize_congestion(
        analytics.get("store_congestion")
    )

    engagement = str(
        analytics.get("engagement")
        or analytics.get("engagement_level")
        or "Unknown"
    )

    peak_zone = (
        analytics.get("peak_zone")
        or analytics.get("most_visited_shelf")
        or "Unknown Zone"
    )

    # ------------------------------------------------------
    # Recommendation container
    # ------------------------------------------------------

    recommendations = []

    # ======================================================
    # RULE 1
    # High Attention + Low Interaction
    # ======================================================

    if (
        attention_score >= config["high_attention"]
        and product_interactions <= config["low_interaction"]
    ):

        recommendations.append(
            create_recommendation(
                priority="HIGH",
                recommendation_type="Product Engagement",
                target=f"Camera {camera_id}" if camera_id else "Current Store",
                action=(
                    "Review product pricing, packaging, visibility, "
                    "and shelf presentation."
                ),
                reason=(
                    f"Customer attention is high ({attention_score:.0f}/100) "
                    f"but product interactions are low "
                    f"({product_interactions:.0f})."
                ),
                expected_impact=(
                    "Improve product interaction and potential conversion."
                ),
            )
        )

    # ======================================================
    # RULE 2
    # High Dwell Time
    # ======================================================

    if average_dwell >= config["high_dwell"]:

        recommendations.append(
            create_recommendation(
                priority="MEDIUM",
                recommendation_type="Dwell Time Optimization",
                target=f"Camera {camera_id}" if camera_id else "Current Store",
                action=(
                    "Review the products and shelf layout in areas "
                    "where customers are spending extended time."
                ),
                reason=(
                    f"Average customer dwell time is "
                    f"{average_dwell:.1f} seconds."
                ),
                expected_impact=(
                    "Identify opportunities to improve customer engagement "
                    "and reduce decision friction."
                ),
            )
        )

    # ======================================================
    # RULE 3
    # Cold / Low Traffic Zone
    # ======================================================

    if (
        current_persons > 0
        and current_persons <= config["low_traffic"]
    ):

        recommendations.append(
            create_recommendation(
                priority="MEDIUM",
                recommendation_type="Shelf / Zone Optimization",
                target=peak_zone,
                action=(
                    "Consider placing a high-performing anchor product "
                    "or promotional display in this low-traffic area."
                ),
                reason=(
                    f"Current traffic is low with "
                    f"{current_persons:.0f} active customer(s)."
                ),
                expected_impact=(
                    "Increase traffic and customer movement toward "
                    "underutilized store zones."
                ),
            )
        )

    # ======================================================
    # RULE 4
    # High Congestion
    # ======================================================

    if store_congestion == "high":

        recommendations.append(
            create_recommendation(
                priority="HIGH",
                recommendation_type="Layout Optimization",
                target=peak_zone,
                action=(
                    "Review aisle spacing, shelf placement, and customer "
                    "movement around the congested zone."
                ),
                reason=(
                    "The store currently reports high customer congestion."
                ),
                expected_impact=(
                    "Improve customer movement and reduce traffic bottlenecks."
                ),
            )
        )

    # ======================================================
    # RULE 5
    # High Interaction Activity
    # ======================================================

    if product_interactions >= config["high_interaction"]:

        recommendations.append(
            create_recommendation(
                priority="MEDIUM",
                recommendation_type="Product Engagement",
                target=peak_zone,
                action=(
                    "Consider strengthening promotions or visibility "
                    "around highly interactive products."
                ),
                reason=(
                    f"{product_interactions:.0f} product interactions "
                    "have been detected."
                ),
                expected_impact=(
                    "Increase engagement around products already attracting "
                    "customer interest."
                ),
            )
        )

    # ======================================================
    # RULE 6
    # Low Attention
    # ======================================================

    if attention_score <= config["low_attention"]:

        recommendations.append(
            create_recommendation(
                priority="MEDIUM",
                recommendation_type="Visibility Optimization",
                target=peak_zone,
                action=(
                    "Review shelf visibility, product positioning, "
                    "signage, and promotional placement."
                ),
                reason=(
                    f"Customer attention score is low "
                    f"({attention_score:.0f}/100)."
                ),
                expected_impact=(
                    "Improve product visibility and customer attention."
                ),
            )
        )

    # ======================================================
    # RULE 7
    # Long Dwell + Low Interaction
    # ======================================================

    if (
        average_dwell >= config["high_dwell"]
        and product_interactions <= config["low_interaction"]
    ):

        recommendations.append(
            create_recommendation(
                priority="HIGH",
                recommendation_type="Conversion Optimization",
                target=peak_zone,
                action=(
                    "Review product pricing, product information, "
                    "packaging, and shelf presentation."
                ),
                reason=(
                    f"Customers are spending approximately "
                    f"{average_dwell:.1f} seconds in the area "
                    f"but interaction remains low."
                ),
                expected_impact=(
                    "Reduce customer hesitation and improve conversion potential."
                ),
            )
        )

    # ======================================================
    # RULE 8
    # Excellent Engagement
    # ======================================================

    if str(engagement).lower() == "excellent":

        recommendations.append(
            create_recommendation(
                priority="LOW",
                recommendation_type="Performance Optimization",
                target=peak_zone,
                action=(
                    "Maintain the current shelf and promotional strategy "
                    "and monitor performance."
                ),
                reason=(
                    "Customer engagement is currently excellent."
                ),
                expected_impact=(
                    "Preserve high-performing customer engagement."
                ),
            )
        )

    # ======================================================
    # RULE 9
    # No Active Customers
    # ======================================================

    if current_persons == 0:

        recommendations.append(
            create_recommendation(
                priority="LOW",
                recommendation_type="Store Activity",
                target="Store",
                action=(
                    "Continue monitoring customer traffic before making "
                    "layout or merchandising changes."
                ),
                reason="No active customers are currently detected.",
                expected_impact=(
                    "Avoid making optimization decisions from insufficient "
                    "real-time traffic data."
                ),
            )
        )

    # ======================================================
    # RULE 10
    # Journey Tracking Opportunity
    # ======================================================

    if tracked_paths > 0:

        recommendations.append(
            create_recommendation(
                priority="LOW",
                recommendation_type="Customer Journey",
                target=peak_zone,
                action=(
                    "Use customer journey and zone-transition data to "
                    "evaluate movement patterns around this area."
                ),
                reason=(
                    f"{tracked_paths:.0f} tracked customer path(s) "
                    "are available."
                ),
                expected_impact=(
                    "Improve layout decisions using observed customer movement."
                ),
            )
        )

    # ======================================================
    # SORT BY PRIORITY
    # ======================================================

    priority_order = {
        "HIGH": 1,
        "MEDIUM": 2,
        "LOW": 3,
    }

    recommendations.sort(
        key=lambda item: priority_order.get(
            item.get("priority"),
            99,
        )
    )

    return recommendations


# ==========================================================
# CAMERA-SPECIFIC WRAPPER
# ==========================================================

def generate_camera_recommendations(
    camera_stats,
    camera_id,
):
    """
    Convenience function for generating recommendations
    for a particular camera.
    """

    return generate_recommendations(
        analytics=camera_stats,
        camera_id=camera_id,
    )


# ==========================================================
# ROLE-SPECIFIC RECOMMENDATIONS
# ==========================================================

def get_role_recommendations(
    recommendations,
    role,
):
    """
    Filter recommendations according to dashboard role.

    Supported roles:
        - admin
        - store_manager
        - marketing_manager
    """

    if not isinstance(recommendations, list):
        return []

    normalized_role = str(role).strip().lower()

    # ------------------------------------------------------
    # ADMIN
    # ------------------------------------------------------

    if normalized_role == "admin":

        return recommendations

    # ------------------------------------------------------
    # STORE MANAGER
    # ------------------------------------------------------

    if normalized_role in {
        "store_manager",
        "store manager",
        "manager",
    }:

        allowed_types = {
            "Shelf / Zone Optimization",
            "Layout Optimization",
            "Product Engagement",
            "Visibility Optimization",
            "Conversion Optimization",
            "Dwell Time Optimization",
            "Customer Journey",
            "Performance Optimization",
            "Store Activity",
        }

        return [
            recommendation
            for recommendation in recommendations
            if recommendation.get("type") in allowed_types
        ]

    # ------------------------------------------------------
    # MARKETING MANAGER
    # ------------------------------------------------------

    if normalized_role in {
        "marketing_manager",
        "marketing manager",
        "marketing",
    }:

        allowed_types = {
            "Product Engagement",
            "Visibility Optimization",
            "Conversion Optimization",
            "Performance Optimization",
            "Dwell Time Optimization",
        }

        return [
            recommendation
            for recommendation in recommendations
            if recommendation.get("type") in allowed_types
        ]

    # ------------------------------------------------------
    # UNKNOWN ROLE
    # ------------------------------------------------------

    return []


# ==========================================================
# SUMMARY FUNCTION
# ==========================================================

def get_recommendation_summary(recommendations):
    """
    Return a compact summary of recommendation counts.
    """

    if not isinstance(recommendations, list):

        return {
            "total": 0,
            "high": 0,
            "medium": 0,
            "low": 0,
        }

    high = 0
    medium = 0
    low = 0

    for recommendation in recommendations:

        priority = str(
            recommendation.get("priority", "")
        ).upper()

        if priority == "HIGH":
            high += 1

        elif priority == "MEDIUM":
            medium += 1

        elif priority == "LOW":
            low += 1

    return {
        "total": len(recommendations),
        "high": high,
        "medium": medium,
        "low": low,
    }