"""Add CoordinateLog

Revision ID: 0644b2a053bf
Revises: aeb60acb4a53
Create Date: 2026-07-25 20:52:26.058319

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '0644b2a053bf'
down_revision = 'aeb60acb4a53'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
