"""Add CoordinateLog

Revision ID: 06ebe0d86b93
Revises: fb0088fa36e2
Create Date: 2026-08-15 20:12:29.130539

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '06ebe0d86b93'
down_revision = 'fb0088fa36e2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
