"""Add CoordinateLog

Revision ID: 10b7a0751b4e
Revises: 8e66da405712
Create Date: 2026-07-30 19:19:58.858223

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '10b7a0751b4e'
down_revision = '8e66da405712'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
