"""Add CoordinateLog

Revision ID: 270663c88015
Revises: 0644b2a053bf
Create Date: 2026-07-26 19:37:53.026606

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '270663c88015'
down_revision = '0644b2a053bf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
