"""Add CoordinateLog

Revision ID: 4def5d5300fb
Revises: 270663c88015
Create Date: 2026-07-26 21:20:47.557449

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '4def5d5300fb'
down_revision = '270663c88015'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
