"""Add CoordinateLog

Revision ID: 4eabfb732657
Revises: c090821911e3
Create Date: 2026-07-30 20:03:58.537074

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '4eabfb732657'
down_revision = 'c090821911e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
