"""Add CoordinateLog

Revision ID: 589dba29b620
Revises: afb335e992e0
Create Date: 2026-07-24 22:20:26.079379

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '589dba29b620'
down_revision = 'afb335e992e0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
