"""Add CoordinateLog

Revision ID: 64ddf2e35daa
Revises: 65542eeebf08
Create Date: 2026-07-24 21:47:20.331000

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '64ddf2e35daa'
down_revision = '65542eeebf08'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
