"""Add CoordinateLog

Revision ID: 65542eeebf08
Revises: 20a98b3303c7
Create Date: 2026-07-24 21:43:32.441945

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '65542eeebf08'
down_revision = '20a98b3303c7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coordinate_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('camera_id', sa.String(length=50), nullable=False),
    sa.Column('shopper_id', sa.String(length=100), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coordinate_logs_shopper_id'), 'coordinate_logs', ['shopper_id'], unique=False)
    op.create_index(op.f('ix_coordinate_logs_store_id'), 'coordinate_logs', ['store_id'], unique=False)
    op.create_index(op.f('ix_coordinate_logs_timestamp'), 'coordinate_logs', ['timestamp'], unique=False)
    op.create_table('tracking_coordinates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('camera_id', sa.String(), nullable=False),
    sa.Column('shopper_id', sa.String(), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tracking_coordinates_timestamp_store', 'tracking_coordinates', ['store_id', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tracking_coordinates_timestamp_store', table_name='tracking_coordinates')
    op.drop_table('tracking_coordinates')
    op.drop_index(op.f('ix_coordinate_logs_timestamp'), table_name='coordinate_logs')
    op.drop_index(op.f('ix_coordinate_logs_store_id'), table_name='coordinate_logs')
    op.drop_index(op.f('ix_coordinate_logs_shopper_id'), table_name='coordinate_logs')
    op.drop_table('coordinate_logs')
    # ### end Alembic commands ###
