"""Add CoordinateLog

Revision ID: 83576526254e
Revises: a247667fee6e
Create Date: 2026-07-25 09:07:46.851771

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '83576526254e'
down_revision = 'a247667fee6e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
