"""Add CoordinateLog

Revision ID: 8b204a23554b
Revises: c687596776ea
Create Date: 2026-08-08 19:00:57.752510

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '8b204a23554b'
down_revision = 'c687596776ea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
