"""Add CoordinateLog

Revision ID: 8e66da405712
Revises: 4def5d5300fb
Create Date: 2026-07-28 17:52:27.490620

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '8e66da405712'
down_revision = '4def5d5300fb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
