"""Add CoordinateLog

Revision ID: a247667fee6e
Revises: 589dba29b620
Create Date: 2026-07-24 22:25:28.613139

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'a247667fee6e'
down_revision = '589dba29b620'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
