"""Add CoordinateLog

Revision ID: aeb60acb4a53
Revises: 83576526254e
Create Date: 2026-07-25 14:25:43.804100

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'aeb60acb4a53'
down_revision = '83576526254e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
