"""Add CoordinateLog

Revision ID: afb335e992e0
Revises: 64ddf2e35daa
Create Date: 2026-07-24 21:54:27.054694

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'afb335e992e0'
down_revision = '64ddf2e35daa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
