"""Add CoordinateLog

Revision ID: c090821911e3
Revises: 10b7a0751b4e
Create Date: 2026-07-30 19:58:47.377809

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'c090821911e3'
down_revision = '10b7a0751b4e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
