"""Add CoordinateLog

Revision ID: c687596776ea
Revises: f229d9144c93
Create Date: 2026-08-08 18:30:06.361890

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'c687596776ea'
down_revision = 'f229d9144c93'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
