"""Add CoordinateLog

Revision ID: e897a9d3e7cd
Revises: f92d16f8508d
Create Date: 2026-08-15 12:12:36.029921

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'e897a9d3e7cd'
down_revision = 'f92d16f8508d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
