"""Add CoordinateLog

Revision ID: f022652dc2f5
Revises: 8b204a23554b
Create Date: 2026-08-08 20:10:10.163539

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'f022652dc2f5'
down_revision = '8b204a23554b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
