"""Add CoordinateLog

Revision ID: f229d9144c93
Revises: 4eabfb732657
Create Date: 2026-08-08 18:27:34.957620

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'f229d9144c93'
down_revision = '4eabfb732657'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
