"""Add M3 and M4 models

Revision ID: f92d16f8508d
Revises: f022652dc2f5
Create Date: 2026-08-15 11:46:53.959820

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'f92d16f8508d'
down_revision = 'f022652dc2f5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('campaign_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('budget', sa.Float(), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('conversions', sa.Integer(), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_table('customer_journeys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('entry_point', sa.String(length=100), nullable=True),
    sa.Column('exit_point', sa.String(length=100), nullable=True),
    sa.Column('zones_visited', sa.JSON(), nullable=False),
    sa.Column('zone_transition_sequence', sa.JSON(), nullable=False),
    sa.Column('total_dwell_time_seconds', sa.Float(), nullable=False),
    sa.Column('zone_dwell_times', sa.JSON(), nullable=False),
    sa.Column('path_length', sa.Float(), nullable=False),
    sa.Column('visit_frequency', sa.Integer(), nullable=False),
    sa.Column('product_interaction_count', sa.Integer(), nullable=False),
    sa.Column('pickup_count', sa.Integer(), nullable=False),
    sa.Column('return_count', sa.Integer(), nullable=False),
    sa.Column('conversion_status', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['shopper_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('heatmap_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('heatmap_type', sa.String(length=50), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=True),
    sa.Column('shelf_id', sa.UUID(), nullable=True),
    sa.Column('grid_data', sa.JSON(), nullable=False),
    sa.Column('time_range_hours', sa.Float(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shelf_id'], ['shelves.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_heatmap_results_heatmap_type'), 'heatmap_results', ['heatmap_type'], unique=False)
    op.create_index(op.f('ix_heatmap_results_store_id'), 'heatmap_results', ['store_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('format', sa.String(length=10), nullable=False),
    sa.Column('generated_by', sa.UUID(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shopper_segments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('segment', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['shopper_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shopper_segments_segment'), 'shopper_segments', ['segment'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=True),
    sa.Column('shelf_id', sa.UUID(), nullable=True),
    sa.Column('camera_id', sa.UUID(), nullable=True),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('acknowledged_by', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shelf_id'], ['shelves.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_alert_type'), 'alerts', ['alert_type'], unique=False)
    op.create_index(op.f('ix_alerts_store_id'), 'alerts', ['store_id'], unique=False)
    op.create_table('product_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('attractiveness_score', sa.Float(), nullable=False),
    sa.Column('shelf_visibility_score', sa.Float(), nullable=False),
    sa.Column('engagement_score', sa.Float(), nullable=False),
    sa.Column('conversion_potential_score', sa.Float(), nullable=False),
    sa.Column('marketing_effectiveness_score', sa.Float(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_scores_product_id'), 'product_scores', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_scores_store_id'), 'product_scores', ['store_id'], unique=False)
    op.create_table('promotions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('promotion_type', sa.String(length=50), nullable=False),
    sa.Column('discount_percent', sa.Float(), nullable=True),
    sa.Column('zone_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('interactions', sa.Integer(), nullable=False),
    sa.Column('conversions', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommendations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('recommendation_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('supporting_metric', sa.String(length=200), nullable=True),
    sa.Column('expected_impact', sa.String(length=200), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('target_zone_id', sa.UUID(), nullable=True),
    sa.Column('target_shelf_id', sa.UUID(), nullable=True),
    sa.Column('target_product_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_shelf_id'], ['shelves.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_zone_id'], ['zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_store_id'), 'recommendations', ['store_id'], unique=False)
    op.drop_index('ix_tracking_coordinates_timestamp_store', table_name='tracking_coordinates')
    op.drop_table('tracking_coordinates')
    op.add_column('coordinate_logs', sa.Column('zone_id', sa.UUID(), nullable=True))
    op.add_column('coordinate_logs', sa.Column('direction', sa.JSON(), nullable=True))
    op.create_foreign_key(None, 'coordinate_logs', 'zones', ['zone_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'coordinate_logs', type_='foreignkey')
    op.drop_column('coordinate_logs', 'direction')
    op.drop_column('coordinate_logs', 'zone_id')
    op.create_table('tracking_coordinates',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('store_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('camera_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('shopper_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('x', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('y', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name='tracking_coordinates_store_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='tracking_coordinates_pkey')
    )
    op.create_index('ix_tracking_coordinates_timestamp_store', 'tracking_coordinates', ['store_id', 'timestamp'], unique=False)
    op.drop_index(op.f('ix_recommendations_store_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_table('promotions')
    op.drop_index(op.f('ix_product_scores_store_id'), table_name='product_scores')
    op.drop_index(op.f('ix_product_scores_product_id'), table_name='product_scores')
    op.drop_table('product_scores')
    op.drop_index(op.f('ix_alerts_store_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_alert_type'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_shopper_segments_segment'), table_name='shopper_segments')
    op.drop_table('shopper_segments')
    op.drop_table('reports')
    op.drop_index(op.f('ix_heatmap_results_store_id'), table_name='heatmap_results')
    op.drop_index(op.f('ix_heatmap_results_heatmap_type'), table_name='heatmap_results')
    op.drop_table('heatmap_results')
    op.drop_table('customer_journeys')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
