"""Add CoordinateLog

Revision ID: fb0088fa36e2
Revises: e897a9d3e7cd
Create Date: 2026-08-15 17:32:37.835631

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'fb0088fa36e2'
down_revision = 'e897a9d3e7cd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
