"""add_coordinate_logs

Revision ID: f6617f5c133a
Revises: 05091aac7a73
Create Date: 2026-07-21 18:56:20.770997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6617f5c133a'
down_revision: Union[str, None] = '05091aac7a73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coordinate_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('shopper_id', sa.String(length=100), nullable=False),
    sa.Column('x_coord', sa.Float(), nullable=False),
    sa.Column('y_coord', sa.Float(), nullable=False),
    sa.Column('zone', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coordinate_logs_id'), 'coordinate_logs', ['id'], unique=False)
    op.create_index(op.f('ix_coordinate_logs_shopper_id'), 'coordinate_logs', ['shopper_id'], unique=False)
    op.create_index(op.f('ix_coordinate_logs_timestamp'), 'coordinate_logs', ['timestamp'], unique=False)
    op.drop_constraint('users_username_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_username_key', 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_coordinate_logs_timestamp'), table_name='coordinate_logs')
    op.drop_index(op.f('ix_coordinate_logs_shopper_id'), table_name='coordinate_logs')
    op.drop_index(op.f('ix_coordinate_logs_id'), table_name='coordinate_logs')
    op.drop_table('coordinate_logs')
    # ### end Alembic commands ###
