import { useEffect, useState, useRef } from "react";
import Layout from "../../components/Layout";
import api from "../../api/client";
import KpiCard from "../../components/dashboard/KpiCard";
import NoAnalyticsNotice from "../../components/dashboard/NoAnalyticsNotice";
import { Map, Footprints, Flame, Users, Activity } from "lucide-react";

export default function HeatmapAnalytics() {
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);
  const canvasRef = useRef(null);

  useEffect(() => {
    async function fetchData() {
      try {
        const res = await api.get("/analytics/heatmap");
        setData(res.data);
      } catch (e) {
        console.error("Failed to fetch heatmap analytics", e);
      } finally {
        setLoading(false);
      }
    }
    fetchData();
    const interval = setInterval(fetchData, 3000);
    return () => clearInterval(interval);
  }, []);

  useEffect(() => {
    if (!data?.heatmap_points?.length || !canvasRef.current) return;
    const canvas = canvasRef.current;
    const ctx = canvas.getContext("2d");
    ctx.clearRect(0, 0, canvas.width, canvas.height);

    // Draw background store grid
    ctx.fillStyle = "#0f172a";
    ctx.fillRect(0, 0, canvas.width, canvas.height);

    ctx.strokeStyle = "#1e293b";
    ctx.lineWidth = 1;
    for (let x = 0; x < canvas.width; x += 40) {
      ctx.beginPath();
      ctx.moveTo(x, 0);
      ctx.lineTo(x, canvas.height);
      ctx.stroke();
    }
    for (let y = 0; y < canvas.height; y += 40) {
      ctx.beginPath();
      ctx.moveTo(0, y);
      ctx.lineTo(canvas.width, y);
      ctx.stroke();
    }

    // Render store zone location markers & place labels
    const storeZones = [
      { name: "Front Entrance", x: (300 / 1920) * canvas.width, y: (200 / 1080) * canvas.height, color: "#38bdf8" },
      { name: "Beverages Aisle", x: (600 / 1920) * canvas.width, y: (300 / 1080) * canvas.height, color: "#22d3a5" },
      { name: "Snacks Aisle", x: (900 / 1920) * canvas.width, y: (300 / 1080) * canvas.height, color: "#f59e0b" },
      { name: "Produce Section", x: (600 / 1920) * canvas.width, y: (700 / 1080) * canvas.height, color: "#a78bfa" },
      { name: "Billing Counter", x: (1200 / 1920) * canvas.width, y: (800 / 1080) * canvas.height, color: "#ef4444" },
      { name: "Dairy & Bakery", x: (900 / 1920) * canvas.width, y: (700 / 1080) * canvas.height, color: "#ec4899" }
    ];

    // Draw Heatmap Points
    data.heatmap_points.forEach((pt) => {
      const x = (pt.x / 1920) * canvas.width;
      const y = (pt.y / 1080) * canvas.height;
      const intensity = pt.intensity || 0.5;

      const rad = 28 * intensity;
      const grad = ctx.createRadialGradient(x, y, 0, x, y, rad);
      grad.addColorStop(0, `rgba(239, 68, 68, ${intensity})`);
      grad.addColorStop(0.5, `rgba(245, 158, 11, ${intensity * 0.6})`);
      grad.addColorStop(1, "rgba(59, 130, 246, 0)");

      ctx.fillStyle = grad;
      ctx.beginPath();
      ctx.arc(x, y, rad, 0, Math.PI * 2);
      ctx.fill();
    });

    // Draw Place / Zone Badges over the canvas
    storeZones.forEach((z) => {
      // Draw location pin circle
      ctx.fillStyle = z.color;
      ctx.beginPath();
      ctx.arc(z.x, z.y, 6, 0, Math.PI * 2);
      ctx.fill();

      // Outer glow pulse
      ctx.strokeStyle = z.color;
      ctx.lineWidth = 1.5;
      ctx.beginPath();
      ctx.arc(z.x, z.y, 12, 0, Math.PI * 2);
      ctx.stroke();

      // Place Label Box
      const text = `📍 ${z.name}`;
      ctx.font = "bold 11px Inter, sans-serif";
      const textWidth = ctx.measureText(text).width;

      const boxX = z.x - textWidth / 2 - 8;
      const boxY = z.y - 28;
      const boxWidth = textWidth + 16;
      const boxHeight = 20;

      // Dark background for badge
      ctx.fillStyle = "rgba(15, 23, 42, 0.85)";
      ctx.strokeStyle = z.color;
      ctx.lineWidth = 1;
      ctx.beginPath();
      ctx.roundRect(boxX, boxY, boxWidth, boxHeight, 6);
      ctx.fill();
      ctx.stroke();

      // Badge Text
      ctx.fillStyle = "#ffffff";
      ctx.fillText(text, boxX + 8, boxY + 14);
    });
  }, [data]);

  const hasData = data && data.has_data !== false;

  return (
    <Layout title="Heatmaps Analytics">
      <div className="space-y-6">
        <div className="bg-slate-900/80 border border-slate-800 rounded-2xl p-5 shadow-lg flex justify-between items-center">
          <div>
            <h1 className="text-xl font-black text-white flex items-center gap-2">
              <Map className="w-5 h-5 text-indigo-400" />
              Spatial Heatmaps & Density Mapping
            </h1>
            <p className="text-xs text-slate-400 mt-1">Real-time coordinate density map generated by ByteTrack bounding boxes mapped to store locations.</p>
          </div>
        </div>

        {loading && !data ? (
          <div className="p-12 text-center text-sm text-slate-400">Loading Heatmap Data...</div>
        ) : !hasData ? (
          <NoAnalyticsNotice title="No Heatmap Data Available" />
        ) : (
          <>
            {/* KPI Overview */}
            <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
              <KpiCard title="Heatmap Coordinates" value={data.heatmap_points?.length || 0} icon={<Map className="w-5 h-5" />} colorClass="text-blue-400" gradientClass="bg-blue-500" />
              <KpiCard title="Peak Density Zones" value={data.peak_areas?.length || 0} icon={<Flame className="w-5 h-5" />} colorClass="text-rose-400" gradientClass="bg-rose-500" />
              <KpiCard title="Hot Zones Count" value={data.hot_zones?.length || 0} icon={<Footprints className="w-5 h-5" />} colorClass="text-emerald-400" gradientClass="bg-emerald-500" />
              <KpiCard title="Cold Zones Count" value={data.cold_zones?.length || 0} icon={<Users className="w-5 h-5" />} colorClass="text-purple-400" gradientClass="bg-purple-500" />
            </div>

            {/* Heatmap Canvas with Place Labels Overlay */}
            <div className="bg-slate-900/80 border border-slate-800 rounded-2xl p-6 shadow-lg">
              <div className="flex justify-between items-center mb-4">
                <h2 className="text-sm font-bold text-white flex items-center gap-2">
                  <Activity className="w-4 h-4 text-emerald-400" />
                  Live Footfall Heatmap Canvas (Store Location Overlays)
                </h2>
                <div className="flex gap-3 text-[10px] font-bold">
                  <span className="flex items-center gap-1 text-rose-400"><span className="w-2.5 h-2.5 rounded-full bg-rose-500"></span> High Traffic</span>
                  <span className="flex items-center gap-1 text-amber-400"><span className="w-2.5 h-2.5 rounded-full bg-amber-500"></span> Medium Traffic</span>
                  <span className="flex items-center gap-1 text-blue-400"><span className="w-2.5 h-2.5 rounded-full bg-blue-500"></span> Low Traffic</span>
                </div>
              </div>
              <div className="w-full h-96 rounded-xl overflow-hidden border border-slate-800 relative bg-slate-950">
                <canvas ref={canvasRef} width={1280} height={450} className="w-full h-full object-cover" />
              </div>
            </div>

            {/* Places & Location Heatmap List */}
            <div className="bg-slate-900/80 border border-slate-800 rounded-2xl p-6 shadow-lg">
              <h3 className="text-sm font-bold text-white mb-4">Store Places & Location Heatmap Status</h3>
              <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                {data.zone_density?.map((z, idx) => (
                  <div key={idx} className="p-4 rounded-xl bg-slate-800/50 border border-slate-700/60 flex flex-col justify-between">
                    <div className="flex justify-between items-start mb-2">
                      <div>
                        <div className="text-sm font-extrabold text-white flex items-center gap-1.5">
                          📍 {z.zone}
                        </div>
                        <div className="text-[11px] text-slate-400 mt-0.5">Location Density Mapping</div>
                      </div>
                      <span className={`text-[10px] font-bold px-2.5 py-1 rounded-full border ${
                        z.density === 'High Density' 
                          ? 'bg-rose-500/20 text-rose-300 border-rose-500/40' 
                          : z.density === 'Medium Density'
                          ? 'bg-amber-500/20 text-amber-300 border-amber-500/40'
                          : 'bg-emerald-500/20 text-emerald-300 border-emerald-500/40'
                      }`}>
                        {z.density}
                      </span>
                    </div>
                    <div className="flex justify-between items-center mt-3 pt-3 border-t border-slate-700/50 text-xs">
                      <span className="text-slate-400">Total Recorded Footfall</span>
                      <span className="font-mono font-bold text-indigo-400">{z.count} visits</span>
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {/* Zone & Shelf Density Breakdown */}
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
              {/* Zone Density */}
              <div className="bg-slate-900/80 border border-slate-800 rounded-2xl p-6 shadow-lg">
                <h3 className="text-sm font-bold text-white mb-4">Zone Density Breakdown</h3>
                <div className="space-y-3">
                  {data.zone_density?.map((z, idx) => (
                    <div key={idx} className="flex justify-between items-center p-3 rounded-xl bg-slate-800/40 border border-slate-800">
                      <div>
                        <span className="text-xs font-bold text-white">{z.zone}</span>
                        <span className="ml-2 text-[10px] px-2 py-0.5 rounded-full bg-slate-700 text-slate-300">{z.density}</span>
                      </div>
                      <span className="text-xs font-mono font-bold text-indigo-400">{z.count} visits</span>
                    </div>
                  ))}
                </div>
              </div>

              {/* Movement Paths */}
              <div className="bg-slate-900/80 border border-slate-800 rounded-2xl p-6 shadow-lg">
                <h3 className="text-sm font-bold text-white mb-4">High Movement Density Corridors</h3>
                <div className="space-y-3">
                  {data.movement_density?.map((p, idx) => (
                    <div key={idx} className="flex justify-between items-center p-3 rounded-xl bg-slate-800/40 border border-slate-800">
                      <div className="text-xs font-bold text-white">{p.path}</div>
                      <span className="text-xs font-mono font-bold text-emerald-400">{p.count} transitions</span>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </>
        )}
      </div>
    </Layout>
  );
}
