export function exportReportAsPDF(reportName: string, category: string, date: string): void {
  // Create a printable HTML layout
  const printContent = `
    <html>
      <head>
        <title>Report - ${reportName}</title>
        <style>
          body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; padding: 40px; color: #333; }
          .header { text-align: center; border-bottom: 2px solid #10b981; padding-bottom: 20px; margin-bottom: 30px; }
          .logo { font-size: 24px; font-weight: bold; color: #0f172a; text-transform: uppercase; letter-spacing: 2px; }
          .logo-accent { color: #10b981; }
          .title { font-size: 28px; font-weight: bold; margin: 20px 0 10px 0; }
          .meta { font-size: 14px; color: #64748b; margin-bottom: 40px; }
          .content { line-height: 1.6; }
          .footer { margin-top: 50px; font-size: 12px; color: #94a3b8; text-align: center; }
          table { width: 100%; border-collapse: collapse; margin-top: 20px; }
          th, td { border: 1px solid #e2e8f0; padding: 12px; text-align: left; }
          th { background-color: #f8fafc; font-weight: 600; }
        </style>
      </head>
      <body>
        <div class="header">
          <div class="logo">Consumer Attention <span class="logo-accent">Mapping System</span></div>
        </div>
        
        <h1 class="title">${reportName}</h1>
        <div class="meta">
          <p><strong>Category:</strong> ${category}</p>
          <p><strong>Generation Date:</strong> ${date}</p>
          <p><strong>Exported:</strong> ${new Date().toLocaleString()}</p>
        </div>

        <div class="content">
          <h3>Summary Data</h3>
          <p>This is an automatically generated system report covering the metrics and analytics for the requested period.</p>
          
          <table>
            <thead>
              <tr>
                <th>Metric</th>
                <th>Value</th>
                <th>Trend</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>Total Tracked Sessions</td>
                <td>1,245</td>
                <td>+12.4%</td>
              </tr>
              <tr>
                <td>Average Dwell Time</td>
                <td>4m 12s</td>
                <td>+2.1%</td>
              </tr>
              <tr>
                <td>Peak Conversion Rate</td>
                <td>18.5%</td>
                <td>+5.4%</td>
              </tr>
              <tr>
                <td>System Anomalies</td>
                <td>0</td>
                <td>-</td>
              </tr>
            </tbody>
          </table>
        </div>

        <div class="footer">
          <p>Generated by Consumer Attention Mapping System - Platform Administration</p>
          <p>Confidential and Proprietary</p>
        </div>
      </body>
    </html>
  `;

  // Open in a new hidden iframe to print
  const iframe = document.createElement('iframe');
  iframe.style.position = 'absolute';
  iframe.style.width = '0px';
  iframe.style.height = '0px';
  iframe.style.border = 'none';
  document.body.appendChild(iframe);

  const doc = iframe.contentWindow?.document;
  if (doc) {
    doc.open();
    doc.write(printContent);
    doc.close();

    // Wait a brief moment for styles to apply before triggering print
    setTimeout(() => {
      iframe.contentWindow?.focus();
      iframe.contentWindow?.print();
      
      // Cleanup after printing dialog closes
      setTimeout(() => {
        document.body.removeChild(iframe);
      }, 1000);
    }, 250);
  }
}
