"""add zone.is_restricted and alert camera/zone/resolved_by

Revision ID: 048a3c587cd5
Revises: 2868e615f11e
Create Date: 2026-08-06 16:50:40.526552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '048a3c587cd5'
down_revision: Union[str, Sequence[str], None] = '2868e615f11e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('camera_id', sa.Integer(), nullable=True))
    op.add_column('alerts', sa.Column('zone_id', sa.Integer(), nullable=True))
    op.add_column('alerts', sa.Column('resolved_by', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_alerts_camera_id'), 'alerts', ['camera_id'], unique=False)
    op.create_index(op.f('ix_alerts_zone_id'), 'alerts', ['zone_id'], unique=False)
    op.create_foreign_key(None, 'alerts', 'users', ['resolved_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'alerts', 'zones', ['zone_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'alerts', 'cameras', ['camera_id'], ['id'], ondelete='SET NULL')
    op.add_column('zones', sa.Column('is_restricted', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zones', 'is_restricted')
    op.drop_constraint(None, 'alerts', type_='foreignkey')
    op.drop_constraint(None, 'alerts', type_='foreignkey')
    op.drop_constraint(None, 'alerts', type_='foreignkey')
    op.drop_index(op.f('ix_alerts_zone_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_camera_id'), table_name='alerts')
    op.drop_column('alerts', 'resolved_by')
    op.drop_column('alerts', 'zone_id')
    op.drop_column('alerts', 'camera_id')
    # ### end Alembic commands ###
