"""add customers, visits, interactions, purchases

Revision ID: 33fd8da68a9a
Revises: 229609ac270e
Create Date: 2026-08-10 23:57:40.039513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33fd8da68a9a'
down_revision: Union[str, Sequence[str], None] = '229609ac270e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_code', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_customer_code'), 'customers', ['customer_code'], unique=True)
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=False)
    op.create_index(op.f('ix_customers_store_id'), 'customers', ['store_id'], unique=False)
    op.create_table('customer_visits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tracking_id', sa.String(length=64), nullable=False),
    sa.Column('track_number', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('entry_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exit_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_dwell_seconds', sa.Float(), nullable=False),
    sa.Column('total_zones_visited', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('camera_id', 'tracking_id', 'entry_time', name='uq_customer_visit_session')
    )
    op.create_index(op.f('ix_customer_visits_camera_id'), 'customer_visits', ['camera_id'], unique=False)
    op.create_index(op.f('ix_customer_visits_customer_id'), 'customer_visits', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_visits_entry_time'), 'customer_visits', ['entry_time'], unique=False)
    op.create_index(op.f('ix_customer_visits_id'), 'customer_visits', ['id'], unique=False)
    op.create_index(op.f('ix_customer_visits_store_id'), 'customer_visits', ['store_id'], unique=False)
    op.create_index(op.f('ix_customer_visits_tracking_id'), 'customer_visits', ['tracking_id'], unique=False)
    op.create_table('purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('transaction_number', sa.String(length=80), nullable=False),
    sa.Column('purchase_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchases_customer_id'), 'purchases', ['customer_id'], unique=False)
    op.create_index(op.f('ix_purchases_id'), 'purchases', ['id'], unique=False)
    op.create_index(op.f('ix_purchases_purchase_time'), 'purchases', ['purchase_time'], unique=False)
    op.create_index(op.f('ix_purchases_store_id'), 'purchases', ['store_id'], unique=False)
    op.create_index(op.f('ix_purchases_transaction_number'), 'purchases', ['transaction_number'], unique=True)
    op.create_table('customer_interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_visit_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('interaction_type', sa.String(length=32), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['customer_visit_id'], ['customer_visits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_interactions_customer_visit_id'), 'customer_interactions', ['customer_visit_id'], unique=False)
    op.create_index(op.f('ix_customer_interactions_id'), 'customer_interactions', ['id'], unique=False)
    op.create_index(op.f('ix_customer_interactions_product_id'), 'customer_interactions', ['product_id'], unique=False)
    op.create_index(op.f('ix_customer_interactions_zone_id'), 'customer_interactions', ['zone_id'], unique=False)
    op.create_table('purchase_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_items_id'), 'purchase_items', ['id'], unique=False)
    op.create_index(op.f('ix_purchase_items_product_id'), 'purchase_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_purchase_items_purchase_id'), 'purchase_items', ['purchase_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_purchase_items_purchase_id'), table_name='purchase_items')
    op.drop_index(op.f('ix_purchase_items_product_id'), table_name='purchase_items')
    op.drop_index(op.f('ix_purchase_items_id'), table_name='purchase_items')
    op.drop_table('purchase_items')
    op.drop_index(op.f('ix_customer_interactions_zone_id'), table_name='customer_interactions')
    op.drop_index(op.f('ix_customer_interactions_product_id'), table_name='customer_interactions')
    op.drop_index(op.f('ix_customer_interactions_id'), table_name='customer_interactions')
    op.drop_index(op.f('ix_customer_interactions_customer_visit_id'), table_name='customer_interactions')
    op.drop_table('customer_interactions')
    op.drop_index(op.f('ix_purchases_transaction_number'), table_name='purchases')
    op.drop_index(op.f('ix_purchases_store_id'), table_name='purchases')
    op.drop_index(op.f('ix_purchases_purchase_time'), table_name='purchases')
    op.drop_index(op.f('ix_purchases_id'), table_name='purchases')
    op.drop_index(op.f('ix_purchases_customer_id'), table_name='purchases')
    op.drop_table('purchases')
    op.drop_index(op.f('ix_customer_visits_tracking_id'), table_name='customer_visits')
    op.drop_index(op.f('ix_customer_visits_store_id'), table_name='customer_visits')
    op.drop_index(op.f('ix_customer_visits_id'), table_name='customer_visits')
    op.drop_index(op.f('ix_customer_visits_entry_time'), table_name='customer_visits')
    op.drop_index(op.f('ix_customer_visits_customer_id'), table_name='customer_visits')
    op.drop_index(op.f('ix_customer_visits_camera_id'), table_name='customer_visits')
    op.drop_table('customer_visits')
    op.drop_index(op.f('ix_customers_store_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_phone'), table_name='customers')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_customer_code'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
