"""add dwell and engagement metrics

Revision ID: 501b560ac256
Revises: c271bf4793ea
Create Date: 2026-07-31 18:21:08.208417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '501b560ac256'
down_revision: Union[str, Sequence[str], None] = 'c271bf4793ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dwell_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('entry_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exit_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dwell_metrics_camera_id'), 'dwell_metrics', ['camera_id'], unique=False)
    op.create_index(op.f('ix_dwell_metrics_customer_id'), 'dwell_metrics', ['customer_id'], unique=False)
    op.create_index(op.f('ix_dwell_metrics_id'), 'dwell_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_dwell_metrics_zone_id'), 'dwell_metrics', ['zone_id'], unique=False)
    op.create_table('engagement_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('standing_time_seconds', sa.Float(), nullable=False),
    sa.Column('interaction_time_seconds', sa.Float(), nullable=False),
    sa.Column('viewing_time_seconds', sa.Float(), nullable=False),
    sa.Column('engagement_score', sa.Float(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_engagement_metrics_camera_id'), 'engagement_metrics', ['camera_id'], unique=False)
    op.create_index(op.f('ix_engagement_metrics_customer_id'), 'engagement_metrics', ['customer_id'], unique=False)
    op.create_index(op.f('ix_engagement_metrics_id'), 'engagement_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_engagement_metrics_zone_id'), 'engagement_metrics', ['zone_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_engagement_metrics_zone_id'), table_name='engagement_metrics')
    op.drop_index(op.f('ix_engagement_metrics_id'), table_name='engagement_metrics')
    op.drop_index(op.f('ix_engagement_metrics_customer_id'), table_name='engagement_metrics')
    op.drop_index(op.f('ix_engagement_metrics_camera_id'), table_name='engagement_metrics')
    op.drop_table('engagement_metrics')
    op.drop_index(op.f('ix_dwell_metrics_zone_id'), table_name='dwell_metrics')
    op.drop_index(op.f('ix_dwell_metrics_id'), table_name='dwell_metrics')
    op.drop_index(op.f('ix_dwell_metrics_customer_id'), table_name='dwell_metrics')
    op.drop_index(op.f('ix_dwell_metrics_camera_id'), table_name='dwell_metrics')
    op.drop_table('dwell_metrics')
    # ### end Alembic commands ###
