"""add entry_time to engagement_metrics

Revision ID: 75e726a32223
Revises: 501b560ac256
Create Date: 2026-07-31 18:37:42.875798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75e726a32223'
down_revision: Union[str, Sequence[str], None] = '501b560ac256'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('engagement_metrics', sa.Column('entry_time', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('engagement_metrics', 'entry_time')
    # ### end Alembic commands ###
