"""add camera.last_processed_video_filename

Revision ID: 8413510b5425
Revises: 048a3c587cd5
Create Date: 2026-08-06 17:53:08.963535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8413510b5425'
down_revision: Union[str, Sequence[str], None] = '048a3c587cd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cameras', sa.Column('last_processed_video_filename', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cameras', 'last_processed_video_filename')
    # ### end Alembic commands ###
