"""baseline

Revision ID: c271bf4793ea
Revises: 
Create Date: 2026-07-31 18:19:00.606308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c271bf4793ea'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cameras', 'location')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cameras', sa.Column('location', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
