"use client";
import React, { useEffect, useState } from 'react';

interface AiInsight {
  id: string;
  type: string;
  title: string;
  description: string;
  severity: 'success' | 'info' | 'warning' | 'critical';
  action: string;
}

export default function AiInsightsTab({ timeFilter = 'all' }: { timeFilter?: string }) {
  const [insights, setInsights] = useState<AiInsight[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    let isMounted = true;
    
    // Wrap inside async function to prevent ESLint set-state-in-effect error
    const fetchInsights = async () => {
      setLoading(true);
      try {
        const res = await fetch(`http://127.0.0.1:9000/api/v1/dashboard/ai-insights?time_filter=${timeFilter}`);
        const data = await res.json();
        if (isMounted && data.status === "success") {
          setInsights(data.data);
        }
      } catch (err) {
        console.error("Failed to fetch AI Insights:", err);
      } finally {
        if (isMounted) setLoading(false);
      }
    };

    fetchInsights();
    
    return () => { isMounted = false; };
  }, [timeFilter]);

  const getSeverityStyles = (severity: string) => {
    switch (severity) {
      case 'success': return { border: 'border-emerald-500/30', bg: 'bg-emerald-500/10', text: 'text-emerald-400', icon: '✨' };
      case 'warning': return { border: 'border-amber-500/30', bg: 'bg-amber-500/10', text: 'text-amber-400', icon: '⚠️' };
      case 'critical': return { border: 'border-rose-500/30', bg: 'bg-rose-500/10', text: 'text-rose-400', icon: '🚨' };
      case 'info':
      default: return { border: 'border-blue-500/30', bg: 'bg-blue-500/10', text: 'text-blue-400', icon: '🧠' };
    }
  };

  return (
    <div className="w-full animate-in fade-in duration-500 text-slate-200">
      <div className="bg-slate-900/80 border border-slate-800 rounded-2xl p-6 shadow-lg mb-6">
        <div className="flex flex-col md:flex-row justify-between items-start md:items-center mb-6">
          <div>
            <h3 className="text-lg font-bold text-slate-200">AI Intelligence Engine</h3>
            <p className="text-slate-400 text-sm mt-1">
              Dynamic recommendations generated by analyzing <code className="text-cyan-400 bg-slate-950 px-1 py-0.5 rounded">supermarket_sales - Sheet1.csv</code>
            </p>
          </div>
          <div className="mt-4 md:mt-0">
             <span className="flex items-center text-xs font-bold text-emerald-400 bg-emerald-500/10 border border-emerald-500/20 px-3 py-2 rounded-lg">
               <span className="w-2 h-2 bg-emerald-500 rounded-full animate-pulse mr-2"></span>
               Dataset Sync Active
             </span>
          </div>
        </div>

        {loading ? (
          <div className="py-12 flex justify-center items-center">
            <span className="text-cyan-400 font-mono text-sm animate-pulse">Running analysis on retail sales data...</span>
          </div>
        ) : insights.length === 0 ? (
          <div className="py-12 flex justify-center items-center text-slate-500 text-sm">
            No insights available for this date range.
          </div>
        ) : (
          <div className="grid grid-cols-1 gap-6">
            {insights.map((insight, idx) => {
              const styles = getSeverityStyles(insight.severity);
              return (
                <div key={idx} className={`border ${styles.border} bg-slate-950 rounded-xl p-5 relative overflow-hidden transition-all hover:bg-slate-900`}>
                  <div className={`absolute top-0 left-0 w-1 h-full ${styles.bg.replace('/10', '')} opacity-50`}></div>
                  <div className="flex flex-col md:flex-row gap-6">
                    <div className="md:w-1/4 shrink-0">
                      <div className="flex items-center space-x-2 mb-2">
                        <span className="text-xl">{styles.icon}</span>
                        <span className="text-xs font-bold text-slate-500 uppercase tracking-wider">{insight.type}</span>
                      </div>
                      <h4 className={`text-base font-bold ${styles.text} mb-1`}>{insight.title}</h4>
                      <p className="text-[10px] text-slate-600 font-mono">Ref: {insight.id}</p>
                    </div>
                    <div className="md:w-3/4 flex flex-col justify-between">
                      <p className="text-sm text-slate-300 leading-relaxed mb-4">{insight.description}</p>
                      <div className="bg-slate-900 border border-slate-800 rounded-lg p-4">
                        <span className="text-[10px] font-bold text-slate-500 uppercase block mb-1">Recommended Action</span>
                        <p className="text-sm text-slate-200">{insight.action}</p>
                      </div>
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        )}
      </div>
    </div>
  );
}