"use client";
import React, { useEffect, useState } from 'react';

interface AiInsight {
  id: string;
  type: string;
  title: string;
  description: string;
  severity: 'success' | 'info' | 'warning' | 'critical';
  action: string;
}

// Matches the values the backend's filter_sales_df_by_time() understands —
// keep in sync with main.py if that set ever changes.
const TIME_FILTER_LABELS: Record<string, string> = {
  all: 'All Recorded Data',
  today: 'Today',
  yesterday: 'Yesterday',
  week: 'Last 7 Days',
  month: 'Last 30 Days',
  quarter: 'Last 90 Days',
  year: 'Last 12 Months',
};

export default function AiInsightsTab({ timeFilter = 'all' }: { timeFilter?: string }) {
  const [insights, setInsights] = useState<AiInsight[]>([]);
  const [loading, setLoading] = useState(true);
  // Distinct from "no insights in this range" — a real fetch/network failure
  // shouldn't silently render the same empty state as a genuinely quiet range.
  const [error, setError] = useState<string | null>(null);
  // Backend now returns a specific message on empty-after-filter results
  // (e.g. "No transactions in the selected range (week).") instead of us
  // always showing one generic hardcoded line regardless of why it's empty.
  const [emptyMessage, setEmptyMessage] = useState<string | null>(null);

  useEffect(() => {
    let isMounted = true;

    // isBackgroundPoll distinguishes the initial/timeFilter-triggered fetch
    // (shows the loading spinner, clears prior error/empty state) from the
    // periodic poll below (silent — a transient hiccup on one tick
    // shouldn't flicker the spinner or wipe out insights that were already
    // showing correctly). Matches the poll pattern already used by
    // AlertsTab/DwellTab/BehaviorTab; this tab previously had none, so an
    // insight derived from live camera data (e.g. "Recent In-Store Dwell
    // Time") only ever updated on mount or when the date range changed.
    const fetchInsights = async (isBackgroundPoll = false) => {
      if (!isBackgroundPoll) {
        setLoading(true);
        setError(null);
        setEmptyMessage(null);
      }
      try {
        const res = await fetch(`/api/backend/v1/dashboard/ai-insights?time_filter=${timeFilter}`, { credentials: 'include' });
        const data = await res.json();
        if (!isMounted) return;

        if (data.status === "success") {
          setInsights(data.data ?? []);
          setEmptyMessage((data.data ?? []).length === 0 ? (data.message || 'No insights available for this date range.') : null);
          setError(null);
        } else if (!isBackgroundPoll) {
          setInsights([]);
          setError(data.message || 'Failed to load AI insights.');
        }
      } catch (err) {
        console.error("Failed to fetch AI Insights:", err);
        if (isMounted && !isBackgroundPoll) {
          setInsights([]);
          setError('Could not reach the AI insights service. Check your connection and try again.');
        }
      } finally {
        if (isMounted) setLoading(false);
      }
    };

    fetchInsights(false);
    const interval = setInterval(() => fetchInsights(true), 10000);

    return () => { isMounted = false; clearInterval(interval); };
  }, [timeFilter]);

  const getSeverityStyles = (severity: string) => {
    switch (severity) {
      case 'success': return { border: 'border-emerald-500/30', bg: 'bg-emerald-500/10', text: 'text-emerald-400', icon: '✨' };
      case 'warning': return { border: 'border-amber-500/30', bg: 'bg-amber-500/10', text: 'text-amber-400', icon: '⚠️' };
      case 'critical': return { border: 'border-rose-500/30', bg: 'bg-rose-500/10', text: 'text-rose-400', icon: '🚨' };
      case 'info':
      default: return { border: 'border-blue-500/30', bg: 'bg-blue-500/10', text: 'text-blue-400', icon: '🧠' };
    }
  };

  return (
    <div className="w-full animate-in fade-in duration-500 text-slate-200">
      <div className="bg-slate-900/80 border border-slate-800 rounded-2xl p-6 shadow-lg mb-6">
        <div className="flex flex-col md:flex-row justify-between items-start md:items-center mb-6">
          <div>
            <h3 className="text-lg font-bold text-slate-200">AI Intelligence Engine</h3>
            <p className="text-slate-400 text-sm mt-1">
              Dynamic recommendations generated by analyzing <code className="text-cyan-400 bg-slate-950 px-1 py-0.5 rounded">supermarket_sales - Sheet1.csv</code>
            </p>
          </div>
          <div className="mt-4 md:mt-0 flex items-center gap-2">
             <span className="flex items-center text-xs font-bold text-cyan-400 bg-cyan-500/10 border border-cyan-500/20 px-3 py-2 rounded-lg">
               {TIME_FILTER_LABELS[timeFilter] ?? timeFilter}
             </span>
             <span className="flex items-center text-xs font-bold text-emerald-400 bg-emerald-500/10 border border-emerald-500/20 px-3 py-2 rounded-lg">
               <span className="w-2 h-2 bg-emerald-500 rounded-full animate-pulse mr-2"></span>
               Dataset Sync Active
             </span>
          </div>
        </div>

        {loading ? (
          <div className="py-12 flex justify-center items-center">
            <span className="text-cyan-400 font-mono text-sm animate-pulse">Running analysis on retail sales data...</span>
          </div>
        ) : error ? (
          <div className="py-12 flex flex-col items-center justify-center text-center gap-1">
            <span className="text-rose-400 text-sm font-medium">{error}</span>
            <span className="text-slate-600 text-xs">Try switching the date range or refreshing the page.</span>
          </div>
        ) : insights.length === 0 ? (
          <div className="py-12 flex justify-center items-center text-slate-500 text-sm text-center px-8">
            {emptyMessage}
          </div>
        ) : (
          <div className="grid grid-cols-1 gap-6">
            {insights.map((insight, idx) => {
              const styles = getSeverityStyles(insight.severity);
              return (
                <div key={idx} className={`border ${styles.border} bg-slate-950 rounded-xl p-5 relative overflow-hidden transition-all hover:bg-slate-900`}>
                  <div className={`absolute top-0 left-0 w-1 h-full ${styles.bg.replace('/10', '')} opacity-50`}></div>
                  <div className="flex flex-col md:flex-row gap-6">
                    <div className="md:w-1/4 shrink-0">
                      <div className="flex items-center space-x-2 mb-2">
                        <span className="text-xl">{styles.icon}</span>
                        <span className="text-xs font-bold text-slate-500 uppercase tracking-wider">{insight.type}</span>
                      </div>
                      <h4 className={`text-base font-bold ${styles.text} mb-1`}>{insight.title}</h4>
                      <p className="text-[10px] text-slate-600 font-mono">Ref: {insight.id}</p>
                    </div>
                    <div className="md:w-3/4 flex flex-col justify-between">
                      <p className="text-sm text-slate-300 leading-relaxed mb-4">{insight.description}</p>
                      <div className="bg-slate-900 border border-slate-800 rounded-lg p-4">
                        <span className="text-[10px] font-bold text-slate-500 uppercase block mb-1">Recommended Action</span>
                        <p className="text-sm text-slate-200">{insight.action}</p>
                      </div>
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        )}
      </div>
    </div>
  );
}